apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-test
  name: argocd-test
  namespace: default
spec:
  ports:
    - name: tcp-8090
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: argocd-test
  sessionAffinity: None
  type: NodePort
